### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by ngosang** [rbrito/enjoyreading-ng#1]
Could you upload a compiled version? Thank You.

**Comment by xHN35RQ** [comment]
For now, you can find a compiled `.xpi` on my branch here: https://github.com/xHN35RQ/enjoyreading-ng/releases/latest

**Comment by xHN35RQ** [comment]
https://github.com/xHN35RQ/enjoyreading-ng/releases/latest

**Comment by rbrito** [comment]
Hi, @ngosang.

I just created our first release: you can find it on https://github.com/rbrito/enjoyreading-ng/releases/latest and the instructions for installation are listed at https://github.com/rbrito/enjoyreading-ng#install

Hope this helps,

Rogério.

**Comment by ngosang** [comment]
Thank you.
