### ISSUE TITLE
Add release for users to download

### ISSUE THREAD

**Issue by ghost** [rbrito/enjoyreading-ng#5]
I guess my release didn't merge across in #3 so you'll have to add your own.

You can copy my release if you want:

https://github.com/xHN35RQ/enjoyreading-ng/releases/latest

Thanks again for keeping this addon alive, I use it quite often. :smile:

**Comment by rbrito** [comment]
Hi.

Your post just prompted me to discover how to add files to what github calls a "release". :)

This means that we have our first release here and this closes #1. :)

Thanks,

Rogério.
